name: call
on:
  workflow_call:
    inputs:
        statement:
          required: true
          type: string

jobs:
  myjob:
    runs-on: ubuntu-20.04
    steps:
      - run: echo ${{inputs.statement}}
