name: call
on:
  workflow_call:
    inputs:
        statement:
          required: true
          type: string

env:
  MERGED_ENV : "${{inputs.statement}} world"

jobs:
  myjob:
    runs-on: ubuntu-20.04
    steps:
      - run: echo ${{env.MERGED_ENV}}
